# Generated by Django 4.2.1 on 2023-05-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=50)),
                ('send_to', models.CharField(max_length=20)),
                ('secret_question', models.TextField(max_length=50)),
                ('secret_answer', models.TextField(max_length=50)),
                ('reply', models.TextField(max_length=50)),
            ],
        ),
    ]
