# Generated by Django 4.2.1 on 2023-05-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='secret_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='secret_question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_to',
            field=models.CharField(),
        ),
    ]
