# Generated by Django 4.2.1 on 2023-05-28 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagingapp', '0002_test_alter_message_message_alter_message_reply_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
